version: '3'
services:
  alpha:
    container_name: alpha
    image: alpha
    ports:
      - 8082:80
  beta:
    container_name: beta
    image: beta
    ports:
      - 8081:80
  nginx-php:
      image: nginx:latest
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on: 
        - alpha
        - beta
      ports: 
        - "8080:80"
      networks: 
        - "ab-php"

networks:
  ab-php: